version: "3.8"
services:
   db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=laravel
      - POSTGRES_DB=laravel
   redis:
     image: redis:alpine
     ports:
       - 6379:6379
